[profile.default]
src = "src"
out = "out"
libs = ["lib"]

solc_version = "0.8.22"

remappings = [
    "@openzeppelin/contracts=node_modules/@openzeppelin/contracts/"
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
